DATAUP-120 Update narrative repo testing to include how to use karma debugger
kbase/narrative pull request #1812
Opened 2020-09-02 22:47 UTC by eamahanna

# Description of PR purpose/changes

Instructions for how to use the karma debugger were added to docs/testing.md. I also created a table of contents for the file and fixed some of the markdown styling. I altered the Readme.md to reference the testing files, so there isn't duplicated documentation. 

# Jira Ticket / Issue #
https://kbase-jira.atlassian.net/browse/DATAUP-120
- [ ] Added the Jira Ticket to the title of the PR e.g. (DATAUP-69 Adds a PR template)

# Testing Instructions
* Details for how to test the PR: 
- [ ] Tests pass in travis and locally 
- [ ] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

# Dev Checklist:

- [ ] My code follows the guidelines at https://sites.google.com/truss.works/kbasetruss/development
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Updating Version and Release Notes (if applicable)

- [ ] [Version has been bumped](https://semver.org/) for each release
- [ ] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

2020-09-03 00:04 UTC, ialarmedalien commented on docs/testing.md
> +`kbase-narrative --no-browser --NotebookApp.allow_origin="*" --ip=127.0.0.1 --port=32323`
these could be broken out into a full line, i.e.

source:
` ``` `
`kbase-narrative --no-browser --NotebookApp.allow_origin="*" --ip=127.0.0.1 --port=32323`
` ``` `

result:
```
kbase-narrative --no-browser --NotebookApp.allow_origin="*" --ip=127.0.0.1 --port=32323
```

2020-09-03 00:06 UTC, ialarmedalien commented on docs/testing.md
> +For python changes, it will require shutting down the notebook, running `scripts/install_narrative.sh -u` and then starting the notebook server up again with kbase-narrative. You can print messages t
> then starting the notebook server up again with kbase-narrative

==> 

then starting the notebook server up again with `kbase-narrative`

2020-09-03 19:07 UTC, leia-sefkin requested changes
Some small edits, but otherwise looking good! 

Wish we could clean up the directory structure a bit - kind of confusing to have testing docs in one place, tests in another, and test config in YET ANOTHER location, but I realize that's not in the scope of this PR.

2020-09-03 19:07 UTC, leia-sefkin commented on docs/testing.md
> +karma start test/ut/karma.conf.js --browsers=Chrome --single-run=false
path should be `test/unit/karma.conf.js`

2020-09-03 19:26 UTC, eamahanna commented on docs/testing.md
> +In the `[users]` and `[token_files]` blocks, two sets of values are needed: test_user and private_user. They don't have any special permissions, they just need to be different users.
@briehl Do you know what the difference is?

2020-09-03 19:28 UTC, eamahanna commented on docs/testing.md
> +1. Install the Narrative and activate its virtualenv (if appropriate)
I think this means your are suppose to activate your conda environment i.e. `conda activate my_narrative_env`. @briehl is this accurate?

2020-09-03 21:59 UTC, briehl commented on docs/testing.md
> +1. Install the Narrative and activate its virtualenv (if appropriate)
Yeah. This doc dates back to the days where it was easiest to use `virtualenv` to install and run things. You could probably rephrase that as just `Install the Narrative using the directions in the README` or something similar.

2020-09-03 22:00 UTC, briehl commented on docs/testing.md
> +In the `[users]` and `[token_files]` blocks, two sets of values are needed: test_user and private_user. They don't have any special permissions, they just need to be different users.
They're meant to be two different, valid, tokens from different accounts. They get that name due to how some tests get run, preventing a "test_user" from reading / writing to a Narrative owned by a "private_user".

2020-09-03 22:06 UTC, briehl commented on docs/testing.md
> +1. Install the Narrative and activate its conda environment (if appropriate)
maybe just `activate its environment`? It doesn't HAVE to be conda, though that's what the default instructions give. I'm sure it'll work fine with venv, or poetry, or pipenv, or whatever.

2020-09-03 22:09 UTC, briehl approved these changes
Looks good to me! I agree with @leia-sefkin 's changes, and made a few comments inline.

2020-09-09 15:22 UTC, eamahanna commented on docs/testing.md
> +In the `[users]` and `[token_files]` blocks, two sets of values are needed: test_user and private_user. They don't have any special permissions, they just need to be different users.
@briehl Is how to get these tokens documented anywhere else in the narrative docs or general KBase docs?

2020-09-09 19:32 UTC, eamahanna commented on docs/testing.md
> +In the `[users]` and `[token_files]` blocks, two sets of values are needed: test_user and private_user. They don't have any special permissions, they just need to be different users.
Added link to developer token documentation

2020-09-09 19:45 UTC, leia-sefkin approved these changes

2020-09-10 14:04 UTC, merged