Updating the PR request template
kbase/narrative pull request #2075
Opened 2021-01-12 23:28 UTC by ialarmedalien

# Description of PR purpose/changes

Update of the PR request template, prompted by the repeated mention of 'travis'; also updated dev docs on Prettier and ESLint.

# Jira Ticket / Issue #
N/A

# Testing Instructions
* Details for how to test the PR: 
- [x] Tests pass in travis and locally   <--- this will soon change!

# Dev Checklist:

- [x] My code follows the guidelines at https://sites.google.com/truss.works/kbasetruss/development
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-01-12 23:39 UTC, briehl requested changes
Looks fine, just a little typo.

2021-01-12 23:39 UTC, briehl commented on .github/pull_request_template.md
> +- [ ] Tests pass in locally and in GitHub Actions
typo - Test pass locally

2021-01-12 23:39 UTC, briehl commented on .github/pull_request_template.md
> +- [ ] (JavaScript) I have run Prettier and ESLint on changed code manually or with a git precommit hook
👍  for clarity!

2021-01-12 23:57 UTC, ialarmedalien commented on .github/pull_request_template.md
> +- [ ] Tests pass in locally and in GitHub Actions
Fixed! Thanks for the good 👀

2021-01-13 00:18 UTC, briehl approved these changes
🚀

2021-01-13 00:18 UTC, merged