DATAUP-314: Job Log Viewer update: add status lines!
kbase/narrative pull request #2223
Opened 2021-03-31 16:37 UTC by ialarmedalien

# Description of PR purpose/changes

# Jira Ticket / Issue #
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-314
- [x] Added the Jira Ticket to the title of the PR (e.g. `DATAUP-69 Adds a PR template`)

# Testing Instructions
* Details for how to test the PR:
- [x] Tests pass locally and in GitHub Actions
- [x] Changes available by spinning up a local narrative, navigating to an app or bulk import cell, and checking out the logs!

# Dev Checklist:

- [x] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] (JavaScript) I have run Prettier and ESLint on changed code manually or with a git precommit hook

2021-03-31 16:40 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/util/jobLogViewer.js
> +            let content = div(
git doesn't understand what has happened here. I've changed `content` from a `const` to a `let`; the DOM structure assigned to `content` has not changed.

2021-03-31 16:40 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/util/jobLogViewer.js
> +                },
`terminated` was missing from the list of states.

2021-03-31 16:41 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/util/jobLogViewer.js
> +            if (developerMode) {
this is an insert -- in developer mode, some extra divs are added with job info and the widget and FSM state.

2021-03-31 16:43 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/util/jobLogViewer.js
> +        function renderJobState(jobState) {
This function renders the job state (surprisingly!)

If the job state is error, an errorDisplay element is added to show the error details.

2021-03-31 16:44 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/util/jobLogViewer.js
> +                renderJobState(lastJobState);
if the job state has changed, update the DOM.

2021-03-31 16:48 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/util/jobLogViewer.js
> +                    awaitingLog = false;
if the log has been deleted, we aren't going to have any joy when listening for it.

2021-03-31 16:50 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/util/jobLogViewer.js
> +            renderJobState({ job_state: 'does_not_exist' });
The job status lines will fill in the message about the job not being found.

2021-03-31 16:53 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/util/jobLogViewer.js
> +            stopJobStatusUpdates();
Obviously if the job is not found, there's no point in getting status updates on it.

2021-03-31 16:58 UTC, ialarmedalien commented on test/unit/spec/util/jobLogViewerSpec.js
> +    }
this info shows up in developer mode; the widget is initialised in dev mode for all these tests.

2021-03-31 17:03 UTC, ialarmedalien commented on test/unit/spec/util/jobLogViewerSpec.js
> +            describe('should be determining the state with no job object', () => {
The status line reads 'Determining job state...' if there is no job state object supplied on widget start.

2021-03-31 17:04 UTC, ialarmedalien commented on test/unit/spec/util/jobLogViewerSpec.js
> +                    const jobId = 'dodgy_job_state_test';
with an invalid job state object, the status line defaults to being 'Determining job state...'

2021-03-31 17:04 UTC, ialarmedalien commented on test/unit/spec/util/jobLogViewerSpec.js
> +                describe(`should create a string for status ${jobState.status}`, () => {
Valid job state object supplied -- the appropriate job status line will be produced.

2021-03-31 17:05 UTC, ialarmedalien commented on test/unit/spec/util/jobLogViewerSpec.js
> +        describe('initial widget state, history mode on', () => {
same as the previous set of tests, but this time with history mode on -- i.e. if the job has gone through the queued and running states, info about queue time and run time will be added to the job status lines.

2021-03-31 17:07 UTC, ialarmedalien commented on test/unit/spec/util/jobLogViewerSpec.js
> +        function createStatusObserver(context, jobMessage) {
although there are similar functions in the `TestUtil` file -- `waitForElement`, `waitForElementState`, etc. -- this is specialised enough to need its own function

2021-03-31 17:08 UTC, ialarmedalien commented on test/unit/spec/util/jobLogViewerSpec.js
> +                        return createStatusObserver(this, formatStatusMessage(jobState)).then(
This promise resolves when there is a change under the job status node -- i.e. the new state is displayed in the UI.

2021-03-31 17:10 UTC, ialarmedalien commented on test/unit/spec/util/jobLogViewerSpec.js
> +                        const logUpdate = logs[acc];
Every time `request-latest-job-log` is called, the next entry in the `logs` array is sent to the widget.

2021-04-07 19:12 UTC, briehl requested changes
Just a couple minor tweaks in the jobLogViewer. Tests are very detailed!

2021-04-09 13:12 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/util/jobLogViewer.js
> +                stopJobStatusUpdates();
Fixed.

2021-04-09 13:15 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/util/jobLogViewer.js
> +         * @param {array{string}} listeners
Done.

2021-04-09 13:20 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/util/jobLogViewer.js
> +                runClock = RunClock.make({
Fixed.

2021-04-09 13:27 UTC, briehl approved these changes
Looks great.

2021-04-09 13:42 UTC, merged