DATAUP-315 batch cancel BE
kbase/narrative pull request #2277
Opened 2021-05-07 17:57 UTC by n1mus

# Description of PR purpose/changes

The front end was modified to be able to send job comm requests to the kernel with a `job_id_list` field instead of `job_id`. This can be handled at `JobComm._handle_comm_message` by detecting whether there is a `job_id_list` field, and if so, split that request into multiple requests with a `job_id`. Similarly to before, these requests are then wrapped in a `JobRequest` class, and delegated to the appropriate method.

# Jira Ticket / Issue #
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-X
- [x] Added the Jira Ticket to the title of the PR (e.g. `DATAUP-69 Adds a PR template`)

# Testing Instructions
* Details for how to test the PR:
- [n/a] Tests pass locally and in GitHub Actions
- [x] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

# Dev Checklist:

- [x] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [n/a] Any dependent changes have been merged and published in downstream modules
- [n/a] (JavaScript) I have run Prettier and ESLint on changed code manually or with a git precommit hook
- [x] (Python) I have run Black and Flake8 on changed Python code manually or with a git precommit hook

# Updating Version and Release Notes (if applicable)

- [n/a] [Version has been bumped](https://semver.org/) for each release
- [n/a] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

2021-05-07 18:47 UTC, briehl requested changes
Looks good! I Just have a couple comments.

2021-05-07 18:47 UTC, briehl commented on src/biokbase/narrative/jobs/jobcomm.py
> +        for job_id in rq["content"]["data"]["job_id_list"]:
This should probably check to see that `job_id_list` is a list, otherwise it'll crash.

2021-05-07 18:47 UTC, briehl commented on src/biokbase/narrative/jobs/jobcomm.py
> +    def _split_request_by_job_id(self, rq: dict) -> list:
For typing, `List[JobRequest]` would be a little more clear.

2021-05-07 18:59 UTC, ialarmedalien commented on src/biokbase/narrative/tests/test_jobcomm.py
> +    def test_split_by_job_id(self):
Could you add in an "integration"-type test, where you run one of the methods with a job_id_list?

2021-05-11 17:59 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/jobcomm.py
> +                }
this message looks fine to me

2021-05-11 18:14 UTC, briehl approved these changes
Looks great.

2021-05-11 18:33 UTC, merged