DRAFT: DATAUP-499: add batch tag
kbase/narrative pull request #2342
Opened 2021-06-30 21:38 UTC by ialarmedalien

Adding code 
Various bits of tidying
Refactoring of Job.from_state (by @sumin) to make job creation smoother and easier

# Description of PR purpose/changes

* Please include a summary of the change and which issue is fixed.
* Please also include relevant motivation and context.
* List any dependencies that are required for this change.

# Jira Ticket / Issue #
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-X
- [ ] Added the Jira Ticket to the title of the PR (e.g. `DATAUP-69 Adds a PR template`)

# Testing Instructions
* Details for how to test the PR:
- [ ] Tests pass locally and in GitHub Actions
- [ ] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

# Dev Checklist:

- [ ] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] (JavaScript) I have run Prettier and ESLint on changed code manually or with a git precommit hook
- [ ] (Python) I have run Black and Flake8 on changed Python code manually or with a git precommit hook

# Updating Version and Release Notes (if applicable)

- [ ] [Version has been bumped](https://semver.org/) for each release
- [ ] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

2021-07-06 16:14 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/appmanager.py
> +                "user": user_id,
this mimics the output from ee2

2021-07-06 16:14 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/appmanager.py
> -            if re.match(r"\d+\.\d+\.\d+", version) is not None:
combined into a single statement

2021-07-06 16:14 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/job.py
> +    def update_state(self, state=None):
cache the updated state

2021-07-06 16:14 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/job.py
> +    def reset_state(self):
mostly for testing

2021-07-06 16:14 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/jobmanager.py
> +JOB_INIT_EXCLUDED_JOB_STATE_FIELDS = [
when the job is initialised, we want the job input data

2021-07-06 18:08 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/job.py
> +    "run_id": None,
Will need to add in `retry_count`, `retry_parent`, and `retry_ids` to this set of attributes once the ee2 API has stabilised.

2021-07-06 20:14 UTC, n1mus commented on src/biokbase/narrative/jobs/job.py
> +        output_state = {key: value for key, value in state.items()}
I think optional: deep copy

2021-07-06 20:16 UTC, n1mus commented on src/biokbase/narrative/jobs/job.py
> +        output_state = {key: value for key, value in state.items()}
More for future proofing. I can get it my next PR

2021-07-06 21:53 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/job.py
> +    def from_state(cls, job_state):
I think it would be better to have this as the default constructor, so that the job object is just a light wrapper around the ee2 data structure.

2021-07-06 22:18 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/job.py
> +    def update_state(self, state=None):
I will add in some extra tests for this

2021-07-07 20:40 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/appmanager.py
> -            token_id=agent_token["id"],
`token_id` has been removed from the job object throughout.

2021-07-07 20:47 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/appmanager.py
> +            },
This data is only available when the app is run. It doesn't get saved in ee2, so if the narrative is reloaded, all this handy info will be lost.

2021-07-07 20:48 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/appmanager.py
> +                BATCH_ID_KEY: batch_submission[BATCH_ID_KEY],
this is currently `parent_job_id` but will get changed to `batch_id` at some point in the near future

2021-07-07 20:49 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/job.py
> +    def final_state(self):
this is just for testing

2021-07-07 20:55 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/jobmanager.py
> -    def _verify_job_parentage(self, parent_job_id, child_job_id):
Remove this job parentage function, which applies to the old parent job format.

2021-07-07 20:55 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/jobmanager.py
> -    def lookup_job_info(self, job_id, parent_job_id=None):
remove these `parent_job_id` arguments throughout as they are not useful (and not implemented in the FE)

2021-07-07 20:56 UTC, ialarmedalien commented on src/biokbase/narrative/tests/narrative_mock/mockclients.py
> +        assert getattr(self.obj, self.method) == self.called, (
black

2021-07-07 20:57 UTC, ialarmedalien commented on src/biokbase/narrative/tests/test_jobmanager.py
> -        new_job = phony_job()
no need to create this phony job -- use one of the existing jobs registered when the job manager starts up

2021-07-07 20:58 UTC, ialarmedalien commented on src/biokbase/narrative/tests/test_jobmanager.py
> +        self.assertEqual(
test the whole data structure, not just the keys

2021-07-07 20:58 UTC, ialarmedalien commented on test/unit/run_tests.py
> +    print(f"Starting local narrative on {JUPYTER_PORT}")
this was all black

2021-07-07 21:11 UTC, briehl requested changes
Couple of minor bookkeeping things, but fine with me. Good bye ugly batch parent-child-relationship juggling!

2021-07-07 22:00 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/job.py
> -        app_version=None,
Done!

2021-07-08 19:57 UTC, briehl approved these changes

2021-07-12 18:26 UTC, merged