Develop to truss
kbase/narrative pull request #2584
Opened 2021-11-05 19:55 UTC by briehl

Resolve conflicts and merge recent changes to the develop branch.

2021-11-05 20:46 UTC, ialarmedalien commented on kbase-extension/static/kbase/js/widgets/function_output/rna-seq/kbaseExpressionSampleTableNew.css
> +.KBaseExpressionSampleTableNew .KBaseExpressionSampleTableNew-header {
oh joy... another random location for css files 😖

2021-11-05 20:48 UTC, ialarmedalien approved these changes
Seems reasonable.

2021-11-08 14:57 UTC, ialarmedalien commented
Did you notice that the same unit test failed in both runs? The code in the module itself does not seem to have changed so presumably it’s something in the deps (bootstrap? or in the css?). Looks like an easy minor fix, just edit line 205 in kbaseNarrativeDataList-spec.js

2021-11-08 14:57 UTC, ialarmedalien requested changes
Looks good - just fix the test that fails in both unit test runs.

2021-11-08 15:55 UTC, ialarmedalien approved these changes
I fixed the datalist test.

2021-11-08 20:54 UTC, briehl commented on kbase-extension/static/kbase/js/widgets/narrative_core/upload/stagingAreaViewer.js
> +                if (_settings.nTable.id !== tableId) {
Make sure we only apply this to the staging area datatable. https://datatables.net/manual/plug-ins/search

2021-11-08 20:59 UTC, merged