Fixing a few easy flake8 errors
kbase/narrative pull request #3311
Opened 2023-07-10 17:54 UTC by ialarmedalien

# Description of PR purpose/changes

A few minor flake8 errors fixed -- mostly things I could do an easy search-and-replace for.

# Jira Ticket / Issue #

Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-X
- [-] Added the Jira Ticket to the title of the PR (e.g. `DATAUP-69 Adds a PR template`)

# Testing Instructions
* Details for how to test the PR:
- [x] Tests pass locally and in GitHub Actions
- [-] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

# Dev Checklist:

- [x] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
[-] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] (Python) I have run Black and Flake8 on changed Python code manually or with a git precommit hook

# Updating Version and Release Notes (if applicable)

- [-] [Version has been bumped](https://semver.org/) for each release
- [-] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

2023-07-10 17:55 UTC, ialarmedalien commented on src/biokbase/narrative/app_util.py
> -    elif var == "workspace_id":
no need for 'else' after 'return' or 'raise'

2023-07-10 17:56 UTC, ialarmedalien commented on src/biokbase/narrative/common/log_proxy.py
> +        if config.user is not None and not database.authenticate(
combine `if`s

2023-07-10 17:56 UTC, ialarmedalien commented on src/biokbase/narrative/contents/manager_util.py
> +    return {
init dict all in one go

2023-07-10 17:57 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/appmanager.py
> +            spec_params_map = {
dict comprehension instead of dict() + generator

2023-07-10 17:58 UTC, ialarmedalien commented on src/biokbase/narrative/jobs/appmanager.py
> +        mapped_value = {}
no need for `else` ==> can decrease indent

2023-07-10 17:58 UTC, ialarmedalien commented on src/biokbase/narrative/tests/test_appeditor.py
> +            re.escape("Can't find sub-node [categories] within path [/] in spec.json"),
make this test more explicit

2023-07-10 17:58 UTC, ialarmedalien commented on src/biokbase/narrative/tests/test_appmanager.py
> +        with contextlib.suppress(Exception):
instead of try / except / pass

2023-07-12 19:07 UTC, briehl requested changes
Looks great, other than a few instances of code duplication. I **think** I caught them all.

2023-07-12 19:07 UTC, briehl commented on src/scripts/kb-log-tail
> +#
More duplication

2023-07-14 13:04 UTC, ialarmedalien commented on src/biokbase/narrative/contents/kbasewsmanager.py
> +# Local
haha!

2023-07-14 13:09 UTC, ialarmedalien commented on src/biokbase/narrative/tests/narrative_mock/mockclients.py
> +        return [get_nar_obj(int(ws_id)) for ws_id in ws_ids]
`id` is a builtin => change the variable name to something else

2023-07-14 14:45 UTC, briehl approved these changes
👍

2023-07-14 15:36 UTC, merged